[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/log/supervisor/supervisord.pid
childlogdir=/var/log/supervisor

[program:serve]
command=serve -s dist -l 3000
directory=/app
user=nextjs
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/serve.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
